// Delt søkeindeks for Fenistra-nettsiden. Lastes av alle sider.
const FENISTRA_SEARCH_INDEX = [
  { title: "Forsiden", url: "index.html", category: "Side", desc: "Fenistra samler kontrakter, arealer, felleskostnader og fakturering i én plattform for effektiv eiendomsforvaltning." },
  { title: "Løsninger", url: "losninger.html", category: "Side", desc: "Se alle 18 løsninger i Fenistra forvaltningssystem, fra kontrakter og felleskostnader til rapportering og kjøpesenterdrift." },
  { title: "Kundehistorier", url: "kunder.html", category: "Side", desc: "Se hvordan Höegh Eiendom, Frydenbø Eiendom, Aspelin Ramm og Backer AS bruker Fenistra i sin daglige eiendomsforvaltning." },
  { title: "Om oss", url: "om-oss.html", category: "Side", desc: "Fenistra er en markedsledende leverandør av forvaltningssystemer for eiendomsbransjen, en del av Visma Property Solutions siden 2020." },
  { title: "KI hos Fenistra", url: "ki.html", category: "Side", desc: "Hvordan Fenistra og Visma Property Solutions jobber med KI i eiendomsforvaltningen, og innovasjonsprosjektet Felix." },
  { title: "Fenistradagene", url: "fenistradagene.html", category: "Side", desc: "Fenistradagene samler alle Fenistra-kunder hvert år i juni for faglig påfyll, nettverksbygging og sosialt samvær." },
  { title: "Kundeteamet", url: "kundeteam.html", category: "Side", desc: "Møt kundeteamet i Fenistra - kundekontakter, brukerstøtte og konsulenter som følger opp kundene våre hver dag." },
  { title: "Produktteamet", url: "produktteam.html", category: "Side", desc: "Møt produktteamet i Fenistra - designere og produktledelse som former løsningene våre." },
  { title: "Priser", url: "priser.html", category: "Side", desc: "Fenistra Standard og Premium - priset etter leieomsetning, ikke antall brukere. Se hva som er inkludert i hver pakke." },
  { title: "Blogg", url: "blogg.html", category: "Side", desc: "Fagartikler om eiendomsforvaltning - felleskostnader, MVA-regelverk, omsetningsleie og kjøpesenterdrift." },
  { title: "Hva er felleskostnadsavregning - og hvorfor blir den ofte feil?", url: "blogg-felleskostnadsavregning.html", category: "Blogg", desc: "Manuell fordeling av felleskostnader er en av de vanligste feilkildene i eiendomsforvaltning." },
  { title: "Omsetningsleie i kjøpesenter: slik sikrer du korrekt rapportering", url: "blogg-omsetningsleie-kjopesenter.html", category: "Blogg", desc: "Omsetningsbasert leie krever løpende oppfølging av hver enkelt leietaker." },
  { title: "MVA ved utleie til næringsdrivende: dette må dere vite", url: "blogg-mva-utleie-naringseiendom.html", category: "Blogg", desc: "Frivillig registrering og justeringsforpliktelser - MVA-reglene er strenge." },

  { title: "Kontrakter", url: "losning-kontrakter.html", category: "Løsning", desc: "Effektiv overvåkning og håndtering av utleie-, fremleie- og interne kontrakter, samlet på tvers av hele porteføljen." },
  { title: "Felleskostnader", url: "losning-felleskostnader.html", category: "Løsning", desc: "Automatisert felleskostnadsavregning med full oversikt over kostnader, fordeling og MVA-behandling." },
  { title: "Arealberegning", url: "losning-arealberegning.html", category: "Løsning", desc: "Nøyaktige arealberegninger som reduserer risikoen for feil i leiekostnader og kvadratmeterpriser, med kobling mot AutoCAD-tegninger." },
  { title: "Justering", url: "losning-justering.html", category: "Løsning", desc: "Et effektivt verktøy for å håndtere MVA og justeringsforpliktelser for utleiere av fast eiendom." },
  { title: "MVA-erklæring", url: "losning-mva-erklaring.html", category: "Løsning", desc: "Automatisert innhenting av nødvendig informasjon ved utleie til MVA-registrerte leietakere." },
  { title: "Fakturering", url: "losning-fakturering.html", category: "Løsning", desc: "Fast, akonto og omsetningsbasert husleie samlet i én løsning, med gjentakende fakturering gjennom hele leieforholdet." },
  { title: "Kjøpesenter", url: "losning-kjopesenter.html", category: "Løsning", desc: "Full oversikt over senterdrift for senterleder, med fokus på butikk, aktiviteter og omsetningsrapportering." },
  { title: "Dokument", url: "losning-dokument.html", category: "Løsning", desc: "Samle kontrakter, tegninger og annen dokumentasjon direkte koblet til riktig eiendom og leieforhold." },
  { title: "Regnskap", url: "losning-regnskap.html", category: "Løsning", desc: "Hold eiendomsøkonomien avstemt og oppdatert, med integrasjon mot regnskapssystemene dere allerede har på plass." },
  { title: "Rapportering", url: "losning-rapportering.html", category: "Løsning", desc: "Standardiserte rapporter og interaktive visualiseringer av porteføljens data og nøkkeltall." },
  { title: "Omsetningsavregning", url: "losning-omsetningsavregning.html", category: "Løsning", desc: "Forenkler og effektiviserer avregningen av omsetningsbasert leie, basert på revisorbekreftet omsetning." },
  { title: "Formuesverdsettelse", url: "losning-formuesverdsettelse.html", category: "Løsning", desc: "Beregning og dokumentasjon av formuesverdi for næringseiendom, som underlag til RF-1098." },
  { title: "Inntektsbudsjett", url: "losning-inntektsbudsjett.html", category: "Løsning", desc: "Bygg inntektsbudsjett direkte fra de faktiske leieforholdene i porteføljen, ikke fra separate regneark." },
  { title: "Innleie", url: "losning-innleie.html", category: "Løsning", desc: "En løsning for deg som leier inn eiendommer, med håndtering av alle leiekontrakter og aktiviteter." },
  { title: "Protokoller", url: "losning-protokoller.html", category: "Løsning", desc: "Verktøy for overtakelse og tilbakelevering av lokaler, med protokoller koblet direkte til riktig kontrakt." },
  { title: "RBO", url: "losning-rbo.html", category: "Løsning", desc: "Enkel innhenting og administrasjon av leietakers årlige, revisorbekreftede omsetningsdata." },
  { title: "Utleie", url: "losning-utleie.html", category: "Løsning", desc: "Holder orden på inntektssiden av den økonomiske forvaltningen i forbindelse med utleie av eiendom og driftstjenester." },
  { title: "Digital signering", url: "losning-digital-signering.html", category: "Løsning", desc: "Signer kontrakter og dokumenter digitalt, direkte i Fenistra. Transaksjonsprodukt inkludert i Fenistra Standard." },

  { title: "Regnskap og ERP-systemer", url: "integrasjon-regnskap-erp.html", category: "Integrasjon", desc: "Tripletex, Xledger, PowerOffice GO, Visma Business NXT, Visma.net og en rekke andre ERP-systemer som SAP, Dynamics og 24SevenOffice." },
  { title: "Årsoppgjør", url: "integrasjon-arsoppgjor.html", category: "Integrasjon", desc: "Integrasjon mot Finale for årsregnskap." },
  { title: "Rapporter og analyse", url: "integrasjon-rapportering.html", category: "Integrasjon", desc: "Kombiner Fenistra-data med Power BI og Maestro for dypere innsikt." },
  { title: "Drift og vedlikehold", url: "integrasjon-drift-vedlikehold.html", category: "Integrasjon", desc: "Koble Fenistra sammen med Properly og FAMAC for drift og vedlikehold av eiendommene." },

  { title: "Hva er et forvaltningssystem?", url: "sporsmal.html", category: "Spørsmål", desc: "Svar på det du lurer på om Fenistra." },
  { title: "Hva inneholder Fenistra Standard?", url: "sporsmal.html", category: "Spørsmål", desc: "Kontrakt, fakturering, regnskap, rapportering, dokument, felleskostnader, omsetningsavregning, formuesverdsettelse og inntektsbudsjett." },
  { title: "Hva inneholder Fenistra Premium?", url: "sporsmal.html", category: "Spørsmål", desc: "Svar på det du lurer på om Fenistra Premium." },
  { title: "Hva er Fenistra Kjøpesenter?", url: "sporsmal.html", category: "Spørsmål", desc: "Svar på det du lurer på om Fenistra Kjøpesenter." },
  { title: "Kan Fenistra integreres med vårt regnskapssystem?", url: "sporsmal.html", category: "Spørsmål", desc: "Svar om integrasjon mot regnskapssystemer." },
  { title: "Hva koster Fenistra?", url: "sporsmal.html", category: "Spørsmål", desc: "Fenistra prises etter leieomsetning, ikke antall brukere." },
  { title: "Hva er forskjellen på Fenistra Standard og Premium?", url: "sporsmal.html", category: "Spørsmål", desc: "Standard for små og mellomstore, Premium for store eiendomsselskaper." },
  { title: "Hvem eier Fenistra?", url: "sporsmal.html", category: "Spørsmål", desc: "Del av Visma Property Solutions siden januar 2020." },
  { title: "Hvor lenge har Fenistra eksistert?", url: "sporsmal.html", category: "Spørsmål", desc: "Røtter tilbake til 1994, navnet Fenistra AS siden 2003." },
  { title: "Hvor mange kunder har Fenistra?", url: "sporsmal.html", category: "Spørsmål", desc: "180+ eiendomsforvaltere i Norge." },
  { title: "Hva er felleskostnadsavregning?", url: "sporsmal.html", category: "Spørsmål", desc: "Fordeling av driftskostnader mellom leietakere, automatisert av Fenistra." },
  { title: "Hva er omsetningsbasert leie (omsetningsleie)?", url: "sporsmal.html", category: "Spørsmål", desc: "Leie knyttet til leietakers omsetning, vanlig i kjøpesentre." },
  { title: "Hva er RBO (revisorbekreftet omsetning)?", url: "sporsmal.html", category: "Spørsmål", desc: "Innhenting av leietakers reviderte omsetningsdata." },
  { title: "Hva er formuesverdsettelse?", url: "sporsmal.html", category: "Spørsmål", desc: "Beregning av formuesverdi for næringseiendom, underlag til RF-1098." },
  { title: "Hva er MVA-erklæring i Fenistra?", url: "sporsmal.html", category: "Spørsmål", desc: "Automatisert innhenting av MVA-erklæringer fra leietakere." },
  { title: "Hva er transaksjonsprodukter?", url: "sporsmal.html", category: "Spørsmål", desc: "MVA-erklæring, RBO, Protokoller og Digital signering." },
  { title: "Kan vi signere kontrakter digitalt i Fenistra?", url: "sporsmal.html", category: "Spørsmål", desc: "Ja, med Digital signering." },
  { title: "Hva er Fenistra Arealberegning?", url: "sporsmal.html", category: "Spørsmål", desc: "Kobler areal direkte til tegning og kontrakt." },
  { title: "Passer Fenistra for oss som leier inn lokaler?", url: "sporsmal.html", category: "Spørsmål", desc: "Ja, med Innleie-løsningen." },
  { title: "Hva er Fenistradagene?", url: "sporsmal.html", category: "Spørsmål", desc: "Årlig samling for Fenistra-kunder, 25+ år med historie." },
  { title: "Jobber Fenistra med kunstig intelligens (KI)?", url: "sporsmal.html", category: "Spørsmål", desc: "Ja, blant annet gjennom Felix." },
  { title: "Hvordan kommer vi i gang med Fenistra?", url: "sporsmal.html", category: "Spørsmål", desc: "Book en demo, eller ta testen for å finne riktig pakke." },
  { title: "Ansatte", url: "ansatte.html", category: "Side", desc: "Menneskene bak Fenistra - kundeteamet og produktteamet som utvikler og drifter systemet." },
  { title: "Redegjørelse etter åpenhetsloven", url: "apenhetsloven.html", category: "Side", desc: "Aktsomhetsvurderinger for grunnleggende menneskerettigheter og anstendige arbeidsforhold hos Visma Property Solutions." },
  { title: "Når kontroll over leiekontrakten blir viktigere enn noensinne", url: "blogg-matrix-samarbeid.html", category: "Blogg", desc: "Fenistra samarbeider med Matrix Insurance om depositum og garantier i næringsleie." },
  { title: "Cookie policy", url: "cookies.html", category: "Side", desc: "Retningslinjer for bruk av cookies (informasjonskapsler) hos Visma Property Solutions." },
  { title: "Datasikkerhet", url: "datasikkerhet.html", category: "Side", desc: "Hvordan Fenistra og Visma Property Solutions ivaretar datasikkerhet, gjennom Visma Security Program og GDPR." },
  { title: "Kjøpesenterløsninger", url: "integrasjon-kjopesenter.html", category: "Integrasjon", desc: "Fenistra integreres med Viametrics og IMAS for ferdselstelling og senterdata." },
  { title: "Alle systemer vi integrerer mot", url: "integrasjoner-alle-systemer.html", category: "Integrasjon", desc: "Full oversikt over alle systemer Fenistra integreres mot: regnskap/ERP, årsoppgjør, drift, rapportering og kjøpesenter." },
  { title: "Integrasjoner", url: "integrasjoner.html", category: "Integrasjon", desc: "Fenistra integreres i dag mot rundt 20 systemer i produksjon hos kunder." },
  { title: "Fenistra Sikkerhetsstyring", url: "losning-sikkerhetsstyring.html", category: "Løsning", desc: "Full oversikt over bankgaranti og depositum i porteføljen, med varsel når sikkerhet mangler eller utløper." },
  { title: "Fenistra Tegning", url: "losning-tegning.html", category: "Løsning", desc: "Ett sentralt arkiv for alle plantegninger, koblet direkte til kontrakt, leietaker og areal." },
  { title: "Sjekk hvilke løsninger som passer for deg", url: "pakke-resultat.html", category: "Side", desc: "Se hvilken Fenistra-pakke som passer for deres portefølje, og book møte med salg." },
  { title: "Personvernerklæring", url: "personvern.html", category: "Side", desc: "Retningslinjer for datahåndtering og personvern hos Visma Property Solutions." },
  { title: "Backer rigger for fremtiden", url: "media-backer.html", category: "I media", desc: "Backer velger Fenistra som nytt forvaltningssystem for sin eiendomsportefølje." },
  { title: "Fenistra Brukerforum 2024", url: "media-brukerforum-2024-invitasjon.html", category: "I media", desc: "Invitasjon til Fenistra Brukerforum 2024, faglig påfyll, nettverksbygging og sosialt samvær." },
  { title: "Oppsummering av Fenistra Brukerforum 2024", url: "media-brukerforum-2024-oppsummering.html", category: "I media", desc: "Innsikt og innovasjon fra bransjens egne foredragsholdere på Fenistra Brukerforum 2024." },
  { title: "Fenistra tar brukeropplevelsen til neste nivå", url: "media-brukeropplevelse-neste-niva.html", category: "I media", desc: "Visma Property Solutions flytter forvaltningssystemet Fenistra over på ny plattform." },
  { title: "Fra budsjett til faktura", url: "media-budsjett-til-faktura.html", category: "I media", desc: "Fenistra Felleskostnader-budsjett gir presis og transparent fordeling, fra budsjett til faktura." },
  { title: "Fenistra+Business NXT", url: "media-business-nxt.html", category: "I media", desc: "Fenistra integrert med Visma Business NXT gir full kontroll på økonomi og eiendomsforvaltning." },
  { title: "Dette må du ha oversikt over i egen eiendomsportefølje", url: "media-eiendomsportefolje-oversikt.html", category: "I media", desc: "Med Fenistra og Create Insight får du oversikt over egen eiendomsportefølje i kombinasjon med markedsdata." },
  { title: "Fenistra forenkler felleskostnadene", url: "media-forenkler-felleskostnadene.html", category: "I media", desc: "Kristin Falch om hvordan Fenistra Felleskostavregning eliminerer manuelle rutiner og reduserer feil." },
  { title: "Derfor har Höegh Eiendom brukt Fenistra i over to tiår", url: "media-hoegh-eiendom.html", category: "I media", desc: "Senior Controller Maren Elise Dalene Torp forteller hvorfor Höegh Eiendom har vært Fenistra-kunde i over 20 år." },
  { title: "Skaper kontinuerlig verdi for kundene", url: "media-kontinuerlig-verdi.html", category: "I media", desc: "Nye Fenistra gir eiendomsselskapene den beste kombinasjonen av fleksibilitet og effektivitet." },
  { title: "Fenistra: Mest komplette løsningen for eiendomsforvaltning", url: "media-mest-komplette-losningen.html", category: "I media", desc: "Hvorfor Fenistra posisjoneres som den mest komplette løsningen for eiendomsforvaltning i Norge." },
  { title: "Slik sikrer du effektiv innhenting av MVA-erklæringer", url: "media-mva-erklaringer.html", category: "I media", desc: "Effektive metoder for å samle inn MVA-erklæringer fra leietakere." },
  { title: "Ny rapport i Fenistra kjøpesenter", url: "media-ny-rapport-kjopesenter.html", category: "I media", desc: "Ny rapport lansert i Fenistra Kjøpesenter, for enda bedre innsikt i senterdriften." },
];
